services:
  comfyui:
    image: ghcr.io/veka-server/docker-comfyui:latest
    container_name: comfyui
    ports:
      - "8188:8188"
    volumes:
      - ${ROOT_PATH}/models/checkpoints:/app/comfyui/models/checkpoints
      - ${ROOT_PATH}/models/clip:/app/comfyui/models/clip
      - ${ROOT_PATH}/models/clip_vision:/app/comfyui/models/clip_vision
      - ${ROOT_PATH}/models/unet:/app/comfyui/models/unet
      - ${ROOT_PATH}/models/vae:/app/comfyui/models/vae
      - ${ROOT_PATH}/models/loras:/app/comfyui/models/loras
      - ${ROOT_PATH}/models/upscale_models:/app/comfyui/models/upscale_models
      - ${ROOT_PATH}/models/controlnet:/app/comfyui/models/controlnet
      - ${ROOT_PATH}/models/output:/app/comfyui/output
      - ${ROOT_PATH}/models/LLM:/app/comfyui/models/LLM
      - ${ROOT_PATH}/models/diffusion_models:/app/comfyui/models/diffusion_models
      - ${ROOT_PATH}/models/text_encoders:/app/comfyui/models/text_encoders
      - ${ROOT_PATH}/models/Joy_caption_two/cgrkzexw-599808:/app/comfyui/models/Joy_caption_two
      - comfyui-inputs:/app/comfyui/input:rw
      - ${ROOT_PATH}/models/workflow:/app/comfyui/user/default/workflows
    networks:
      - no-internet
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    labels:
      - "homepage.group=AI & Image Generation"
      - "homepage.name=ComfyUI"
      - "homepage.icon=/icons/comfyui.png"
      - "homepage.href=https://comfyui.loc.ovh"
      - "homepage.description=Workflow basé sur les nœuds pour la génération d'images"
      - "homepage.weight=1"

  docker-download-models:
    image: ghcr.io/veka-server/docker-download-models:latest
    container_name: docker-download-models
    volumes:
      - ${ROOT_PATH}/models:/models
    restart: no
    labels:
      - "homepage.group=AI & Image Generation"
      - "homepage.name=Download Models"
      - "homepage.icon=/icons/download.png"
      - "homepage.description=Gestionnaire de téléchargement de modèles"


volumes:
  comfyui-inputs:
