include:
  - ./services/infrastructure/docker-compose.yml
  - ./services/ai-llm/docker-compose.yml
  - ./services/image-generation/docker-compose.yml
  - ./services/browsing/docker-compose.yml
  - ./services/network/docker-compose.yml
  - ./services/gaming/docker-compose.yml
  - ./services/utilities/docker-compose.yml
  - ./services/media/docker-compose.yml

networks:
  no-internet:
    driver: bridge
    internal: true
    
  traefik:
    driver: bridge
    internal: true    

  internal-fixed:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.125.0.0/24

  custom-network:
    driver: bridge
    
  mcp-network:
    driver: bridge
    internal: true
