networks:
  no-internet:
    driver: bridge
    internal: true # pas d'accès internet

  internal-fixed:
    driver: bridge
    internal: true # pas d'accès internet
    ipam:
      config:
        - subnet: 172.125.0.0/24

  custom-network:
    driver: bridge

volumes:
  comfyui-inputs:
  portainer_data:
  immich-model-cache:
  hyphanet_data:

services:
  dnsrelay:
    image: 4km3/dnsmasq:latest
    container_name: dnsrelay
    command:
      - --no-daemon
      - --log-queries
      - --server=192.168.1.182
      - --listen-address=0.0.0.0
      - --bind-interfaces
      - --address=/.loc.ovh/172.125.0.11
    restart: unless-stopped
    networks:
      internal-fixed:
        ipv4_address: 172.125.0.11
      custom-network:

  nginx-reverse-proxy:
    image: ghcr.io/veka-server/docker-nginx-reverse-proxy:latest
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      internal-fixed:
        ipv4_address: 172.125.0.12
      no-internet:
      custom-network:

  comfyui:
    image: ghcr.io/veka-server/docker-comfyui:latest
    container_name: comfyui
    ports:
      - "8188:8188"
    volumes:
      - /home/veka/models/checkpoints:/app/comfyui/models/checkpoints
      - comfyui-inputs:/app/comfyui/input:rw
    networks:
      - no-internet
    restart: unless-stopped

  open-webui-standalone:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui-standalone
    ports:
      - "8080:8080"
    networks:
      - no-internet
    restart: unless-stopped

  immich_postgres:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    container_name: immich_postgres
    environment:
      POSTGRES_USER: immich
      POSTGRES_PASSWORD: password
      POSTGRES_DB: immich
    networks:
      - no-internet
    restart: unless-stopped

  immich_server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich_server
    depends_on:
      - immich_postgres
      - immich_redis
    networks:
      - no-internet
    restart: unless-stopped

  immich_redis:
    image: valkey/valkey:8-bookworm
    container_name: immich_redis
    networks:
      - no-internet
    restart: unless-stopped

  immich_machine_learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich_machine_learning
    networks:
      - no-internet
    restart: unless-stopped

  explorer:
    image: hurlenko/filebrowser
    container_name: explorer
    ports:
      - "8081:8080"
    networks:
      - no-internet
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - no-internet
      - custom-network
    restart: unless-stopped

  tor:
    image: ghcr.io/veka-server/docker-tor-proxy:latest
    container_name: tor
    networks:
      - no-internet
    restart: unless-stopped

  brave:
    image: kasmweb/brave:1.17.0-rolling-weekly
    container_name: brave
    networks:
      - no-internet
    restart: unless-stopped

  tor-browser:
    image: kasmweb/tor-browser:1.17.0-rolling-daily
    container_name: tor-browser
    networks:
      - no-internet
    restart: unless-stopped

  tor-browser2:
    image: kasmweb/tor-browser:1.17.0-rolling-daily
    container_name: tor-browser2
    networks:
      - no-internet
    restart: unless-stopped

  browser-tor-novnc:
    image: ghcr.io/veka-server/docker-surf-no-vnc:main
    container_name: browser-tor-novnc
    networks:
      - no-internet
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - no-internet
      - custom-network
    restart: unless-stopped

  hyphanet:
    image: docker-homelab-hyphanet
    container_name: hyphanet
    networks:
      - no-internet
    restart: unless-stopped

  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    ports:
      - "25565:25565"
    networks:
      - no-internet
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    networks:
      - no-internet
    restart: unless-stopped
