include:
  - ./services/infrastructure/docker-compose.yml
  - ./services/ai-llm/docker-compose.yml
  - ./services/image-generation/docker-compose.yml
  - ./services/browsing/docker-compose.yml
  - ./services/network/docker-compose.yml
  - ./services/gaming/docker-compose.yml
  - ./services/utilities/docker-compose.yml
  - ./services/media/docker-compose.yml

networks:
  no-internet:
    driver: bridge
    internal: true
    name: no-internet
    
  traefik:
    driver: bridge
    internal: true    
    name: traefik

  internal-fixed:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.125.0.0/24
    name: internal-fixed

  custom-network:
    driver: bridge
    name: custom-network
    
  mcp-network:
    driver: bridge
    internal: true
    name: mcp-network

# Authentification GHCR
x-registries:
  ghcr.io:
    username: ${GHCR_USERNAME}
    password: ${GHCR_TOKEN}