http:
  routers:
    traefik-dashboard:
      rule: "Host(`traefik.loc.ovh`)"
      entrypoints:
        - web
      service: api@internal
#      tls:
#        certResolver: letsencrypt
      middlewares:
        - auth

  middlewares:
    redirect-https:
      redirectScheme:
        scheme: https
        permanent: true
    
    auth:
      basicAuth:
        users:
          - "admin:$apr1$tN9Hh8cT$1qZKaiSA71yY5CZpKtdbx."