http:
  routers:
    traefik-dashboard:
      rule: "Host(`traefik.loc.ovh`)"
      entrypoints:
        - websecure
      service: api@internal
      tls:
        certResolver: letsencrypt
      middlewares:
        - auth

  middlewares:
    redirect-https:
      redirectScheme:
        scheme: https
        permanent: true
    
    auth:
      basicAuth:
        users:
          - "admin:$$2y$$05$$test"