http:
  routers:
    traefik-dashboard:
      rule: "Host(`traefik.loc.ovh`)"
      entrypoints:
        - web
        - websecure
      service: api@internal
      tls: {}
      middlewares:
        - auth

  middlewares:
    auth:
      basicAuth:
        users:
          - "admin:$apr1$tN9Hh8cT$1qZKaiSA71yY5CZpKtdbx."
    websocket:
      headers:
        customRequestHeaders:
          Connection: "upgrade"
          Upgrade: "websocket"

  serversTransports:
    skip-verify:
      insecureSkipVerify: true
      
tls:
  certificates:
    - certFile: /certs/fullchain.pem
      keyFile: /certs/privkey.pem