# Configuration globale de Traefik
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Point d'entrée API et Dashboard
api:
  dashboard: true
  debug: true

# Points d'entrée (entrypoints)
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          regex: "^http://(.*)$"
          replacement: "https://$1"
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

# Fournisseur Docker
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    swarmMode: false
    watch: true
    network: custom-network
  file:
    filename: /dynamic.yml
    watch: true

# Configuration ACME (Let's Encrypt)
certificatesResolvers:
  letsencrypt:
    acme:
      email: ${ACME_EMAIL:-admin@loc.ovh}
      storage: /acme.json
      httpChallenge:
        entryPoint: web

# Logs
log:
  level: INFO
  filePath: /var/log/traefik/traefik.log

accessLog:
  filePath: /var/log/traefik/access.log