services:
  explorer:
    image: hurlenko/filebrowser
    container_name: explorer
    environment:
      - FB_BASEURL=/filebrowser
    volumes:
      - ${ROOT_PATH}:/data/veka
      - ${ROOT_PATH}/config-explorer:/config
    networks:
      - no-internet
      - traefik
    restart: unless-stopped
    labels:
      - "homepage.group=Utilities"
      - "homepage.name=File Explorer"
      - "homepage.icon=filebrowser.png"
      - "homepage.href=https://explorer.loc.ovh/"
      - "homepage.description=Explorateur de fichiers"
      - "traefik.enable=true"
      - "traefik.http.routers.explorer.rule=Host(`explorer.loc.ovh`)"
      - "traefik.http.routers.explorer.entrypoints=web,websecure"
      - "traefik.http.routers.explorer.tls=true"
      - "traefik.http.services.explorer.loadbalancer.server.port=8080"

  ssps:
    image: ghcr.io/veka-server/ssps:master
    container_name: ssps
    networks:
      - no-internet
      - traefik
    env_file:
      - ../../.env
    volumes:
      - ${ROOT_PATH}/ssps/.env.yaml:/var/www/html/.env.yaml
      - ${ROOT_PATH}/ssps/:/var/www/html/bdd/
    restart: unless-stopped
    labels:
      - "homepage.group=Utilities"
      - "homepage.name=SSPS"
      - "homepage.icon=passwork.png"
      - "homepage.href=https://ssps.loc.ovh/"
      - "homepage.description=Gestionnaire de mot de passe"
      - "traefik.enable=true"
      - "traefik.http.routers.ssps.rule=Host(`ssps.loc.ovh`)"
      - "traefik.http.routers.ssps.entrypoints=web,websecure"
      - "traefik.http.routers.ssps.tls=true"
      - "traefik.http.services.ssps.loadbalancer.server.port=80"