services:
  explorer:
    image: hurlenko/filebrowser
    container_name: explorer
    environment:
      - FB_BASEURL=/filebrowser
    volumes:
      - ${ROOT_PATH}:/data/veka
      - ${ROOT_PATH}/config-explorer:/config
    networks:
      - no-internet
    restart: unless-stopped
    labels:
      - "homepage.group=Utilities"
      - "homepage.name=File Explorer"
      - "homepage.icon=filebrowser.png"
      - "homepage.href=https://explorer.loc.ovh/"
      - "homepage.description=Explorateur de fichiers"
