# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /
    refresh: 500 # optional, in ms

- search:
    provider: searxng
    focus: true # Optional, will set focus to the search bar on page load
#    url: https://searxng.loc.ovh?q=
    url: https://google.fr?q=
    target: _blank
