# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /
    refresh: 500 # optional, in ms

- search:
    provider: duckduckgo
    target: _blank
