services:
  brave:
    image: kasmweb/brave:1.17.0-rolling-weekly
    container_name: brave
    environment:
      VNC_PW: password
      LAUNCH_URL: http://hub.loc.ovh
    ports:
      - "6901:6901"
    restart: unless-stopped
    shm_size: 4g
    networks:
      no-internet:
      internal-fixed:
        ipv4_address: 172.125.0.13
      traefik:
    dns:
      - 172.125.0.11
    labels:
      - "homepage.group=Browsing"
      - "homepage.name=Brave Browser"
      - "homepage.icon=brave.png"
      - "homepage.href=https://brave.loc.ovh/"
      - "homepage.description=Navigateur Web VNC"
      - "traefik.enable=true"
      - "traefik.http.routers.brave.rule=Host(`brave.loc.ovh`)"
      - "traefik.http.routers.brave.entrypoints=web,websecure"
      - "traefik.http.routers.brave.tls=true"
      - "traefik.http.services.brave.loadbalancer.server.port=6901"
#      - "traefik.http.routers.brave.middlewares=websocket"
      - "traefik.http.services.brave.loadbalancer.passHostHeader=true"
      - "traefik.http.services.brave.loadbalancer.server.scheme=https"

  browser-tor-novnc:
    image: ghcr.io/veka-server/docker-surf-no-vnc:main
    container_name: browser-tor-novnc
    restart: unless-stopped
    volumes:
      - ${ROOT_PATH}/mangas/local:/localdownload
    networks:
      - no-internet
      - traefik
    labels:
      - "homepage.group=Browsing"
      - "homepage.name=Browser Tor NoVNC"
      - "homepage.href=https://browser-tor-novnc.loc.ovh/vnc.html"
      - "homepage.icon=chromium.png"
      - "homepage.description=Navigateur Tor sans VNC"
      - "traefik.enable=true"
      - "traefik.http.routers.browser-tor-novnc.rule=Host(`browser-tor-novnc.loc.ovh`)"
      - "traefik.http.routers.browser-tor-novnc.entrypoints=web,websecure"
      - "traefik.http.routers.browser-tor-novnc.tls=true"
      - "traefik.http.services.browser-tor-novnc.loadbalancer.server.port=6080"