services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MAX_PLAYERS: "20"
      MOTD: "Serveur Veka"
      ENFORCE_WHITELIST: "TRUE"
      WHITELIST: "vekam,EmilieJasmine14"
      OPS: "vekam"
      ONLINE_MODE: "TRUE"
      DIFFICULTY: "normal"
      VERSION: "1.21.8"
      MODE: "survival"
      PVP: "true"
      LEVEL_TYPE: "DEFAULT"
      SERVER_PORT: "25565"
    volumes:
      - ${ROOT_PATH}/minecraft-data:/data
    restart: unless-stopped
    labels:
      - "homepage.group=Gaming"
      - "homepage.name=Minecraft"
      - "homepage.icon=minecraft.png"
      - "homepage.href=http://localhost:25565"
      - "homepage.description=Serveur Minecraft Veka"

networks:
  no-internet:
    external: true
